---
- name: Converge
  hosts: all
  vars:
    binary_source: ../../../../../../build
    binary_name: modern-go-application-docker
  roles:
    # - role: application-setup
    - role: deployment
  pre_tasks:
    - name: Create valid application configuration
      template:
        src: ../../../../../../config.toml.dist
        dest: "/home/app/etc/app.toml"
        owner: "app"
        group: "app"
        mode: 0600
