version: 2.1

executors:
    go:
        parameters:
            build_image:
                type: string
                default: "circleci/golang"
                description: Go build image
            go_version:
                type: string
                default: "1.14"
                description: Go build image version
        docker:
            -   image: << parameters.build_image >>:<< parameters.go_version >>
                environment:
                    GOFLAGS: -mod=readonly

jobs:
    tests:
        executor: go

        steps:
            - checkout

            -   run:
                    name: Run tests
                    command: |
                        if [ $CIRCLE_NODE_TOTAL -gt 1 ]; then
                            export TEST_PKGS=$(echo `go list ./... | circleci tests split`)
                            export TEST_REPORT_NAME=results_${CIRCLE_NODE_INDEX}.xml
                        fi

                        make test

            -   store_test_results:
                    path: build/test_results/

    lint:
        executor: go

        steps:
            - checkout

            -   run:
                    name: Run linter
                    command: make lint

workflows:
    version: 2
    build:
        jobs:
            - tests
            - lint
