---
-
    name: Ensure application user is present
    user:
        name: "{{ app_user_name }}"
        shell: /bin/bash
        groups: docker
        append: true
        state: present
    register: user

-
    name: Add application user authorized keys
    authorized_key:
        user: "{{ user.name }}"
        key: "{{ item }}"
        state: present
    with_items: "{{ app_user_authorized_keys }}"
    no_log: true

-
    name: Ensure required directories exist
    file:
        path: "{{ user.home }}/{{ item }}"
        state: directory
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: 0700
    with_items:
        - etc

        - .config/systemd/user
