workspace:
  base: /cicd

pipeline:
  create_cluster:
    image: banzaicloud/ci-pipeline-client:0.12
    action: EnsureCluster

  {{{{- if .pipeline.build_image.enabled }}}}
  test:
    image: golang:1.13
    commands: make check
    environment:
      GOFLAGS: -mod=readonly

  build_image:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: '{{ .CICD_REPO }}'
    tags: '{{ trunc 7 .CICD_COMMIT_SHA }}'
    secretFrom:
      DOCKER_USERNAME:
        # name:
        keyRef: username
      DOCKER_PASSWORD:
        # name:
        keyRef: password
  {{{{- end }}}}

  package_application:
    when:
      branch:
        include: [master]
    image: alpine/helm:2.14.2
    commands:
      - helm init --client-only
      - helm repo add stable https://kubernetes-charts.storage.googleapis.com
      - helm repo add banzaicloud-stable http://kubernetes-charts.banzaicloud.com/branch/master
      - helm package ./.banzaicloud/charts/spotguide-modern-go-application

  install_mysql_user_credentials_secret:
    when:
      branch:
        include: [master]
    image: banzaicloud/ci-pipeline-client:0.12
    action: InstallSecret
    clusterSecret:
      name: '{{ .CICD_REPO_NAME }}-mysql'
      # sourceSecretName:
      # namespace:
      merge: true
      spec:
        {{{{- if .pipeline.deploy_application.deployment.values.mysql.enabled }}}}
        - name: mysql-username
          value: app
        {{{{ else }}}}
        - name: mysql-username
          source: username
        {{{{- end }}}}
        - name: mysql-password
          source: password

  {{{{- if .pipeline.deploy_application.deployment.values.mysql.enabled }}}}
  install_mysql_root_password_secret:
    when:
      branch:
        include: [master]
    image: banzaicloud/ci-pipeline-client:0.12
    action: InstallSecret
    clusterSecret:
      name: '{{ .CICD_REPO_NAME }}-mysql'
      # sourceSecretName:
      # namespace:
      merge: true
      spec:
        - name: mysql-root-password
          source: password
  {{{{- end }}}}

  deploy_application:
    when:
      branch:
        include: [master]
    image: banzaicloud/ci-pipeline-client:0.12
    action: EnsureDeployment
    deployment:
      name: './spotguide-modern-go-application-0.3.0.tgz'
      # namespace:
      reuseValues: true
      releaseName: '{{ .CICD_REPO_NAME }}'
      wait: true
      timeout: 900
      values:
        nameOverride: '{{ .CICD_REPO_NAME }}'
        image:
          {{{{- if .pipeline.build_image.enabled }}}}
          repository: '{{ .CICD_REPO }}'
          tag: '{{ trunc 7 .CICD_COMMIT_SHA }}'
          {{{{- end }}}}
          pullPolicy: Always
        config:
          opencensus:
            prometheus:
              enabled: true
        {{{{- if .platform.AutoDNSEnabled }}}}
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: traefik
            traefik.ingress.kubernetes.io/redirect-regex: ^http://(.*)
            traefik.ingress.kubernetes.io/redirect-replacement: https://$1
            traefik.ingress.kubernetes.io/redirect-permanent: "true"
          hosts:
            - 'app-{{ .CICD_REPO_NAME }}.{{ .CLUSTER_NAME }}.{{ .ORG_NAME }}.{{ .DOMAIN_NAME }}'
        {{{{ else }}}}
        service:
          type: LoadBalancer
        {{{{- end }}}}

        mysql:
          existingSecret: '{{ .CICD_REPO_NAME }}-mysql'
          mysqlUser: app
          metrics:
            enabled: true
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "9104"
            livenessProbe:
              initialDelaySeconds: 200
